name: social_mate_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  go_router: ^17.0.1
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  injectable_generator: ^2.11.1
  flutter_screenutil: ^5.9.3
  rename: ^3.1.0
  change_app_package_name: ^1.5.0
  smooth_page_indicator: ^2.0.1
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  my_flutter_toolkit:
    git:
      url: https://github.com/AmrSalahDev/MyFlutterToolKit.git
      ref: main  
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  talker_bloc_logger: ^5.1.10
  bloc_concurrency: ^0.3.0
  extension: ^1.0.0
  flutter_svg: ^2.2.3
  toastification: ^3.0.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  dotted_border: ^3.1.0
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/core/assets_gen

  integrations:
    image: true
    flutter_svg: true
    lottie: false

  colors:
    inputs:
      - assets/colors/colors.xml

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: AppStrings # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: lib/core/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/core/l10n/generated # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
  

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

    - .env 

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
